### ISSUE TITLE
Strange output for parse error

### ISSUE THREAD

**Issue by brother** [idank/explainshell#134]
Looks like all (? at least the few I tested) parse errors will return the same error and it's not super helpful.

Example in  http://explainshell.com/explain?cmd=if+false or http://explainshell.com/explain?cmd=while+true

**Comment by brother** [comment]
Actually looks like it works as it suppose to in http://explainshell.com/explain?cmd=case+in+%24apa

**Comment by idank** [comment]
Yeah, unfortunately the errors aren't as descriptive as one would expect. The observant reader will notice that this is similar to how bash's lack of user-friendly errors as well (since explainshell uses a port of its parser):

$ bash -c 'if false'
bash: -c: line 1: syntax error: unexpected end of file

I believe a certain class of errors do print slightly more descriptive messages, like http://explainshell.com/explain?cmd=if+foo%3B+done

**Comment by brother** [comment]
ok. not the same as bash but I see the point.


brother ~$ if foo; done
bash: syntax error near unexpected token `done'
